# Generated by Django 4.2 on 2024-05-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='postcode',
            new_name='eircode',
        ),
    ]
