# Generated by Django 4.2 on 2024-05-04 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('message', models.TextField(blank=True, help_text='Optionally, add a message to display on the website.')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city_or_town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('eircode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='profiles.profile')),
            ],
        ),
    ]
